"""Assembly include emitters for graphics assets."""

from __future__ import annotations

from typing import Any, Dict, List


def build_bitmap_asm_include(manifest: Dict[str, Any]) -> str:
    addresses = manifest["addresses"]
    vic = manifest["vic_registers"]
    return "\n".join(
        [
            "; Generated by c64-ultimate-mcp graphics tools",
            f"BITMAP_ADDR = ${addresses['bitmap']:04X}",
            f"SCREEN_ADDR = ${addresses['screen']:04X}",
            f"COLOR_ADDR  = ${addresses['color']:04X}",
            "",
            "bitmap_data:",
            f'    .incbin "{manifest["output_files"]["bitmap"]}"',
            "screen_data:",
            f'    .incbin "{manifest["output_files"]["screen"]}"',
            "color_data:",
            f'    .incbin "{manifest["output_files"]["color"]}"',
            "",
            "; VIC-II setup snippet",
            f"VIC_D011 = {vic['d011']}",
            f"VIC_D016 = {vic['d016']}",
            f"VIC_D018 = {vic['d018']}",
            "",
            "    lda #VIC_D011",
            "    sta $d011",
            "    lda #VIC_D016",
            "    sta $d016",
            "    lda #VIC_D018",
            "    sta $d018",
        ]
    ) + "\n"


def build_sprite_asm_include(manifest: Dict[str, Any], sprite_meta: List[Dict[str, Any]]) -> str:
    lines = ["; Generated by c64-ultimate-mcp graphics tools"]
    for meta in sprite_meta:
        label = f"sprite_{meta['index']:03d}"
        lines.append(f"{label}:")
        lines.append(f'    .incbin "{meta["file"]}"')
    return "\n".join(lines) + "\n"
