"""BASIC loader emitters."""

from __future__ import annotations

from typing import Any, Dict, Iterable, List


def _data_lines(data: Iterable[int], start_line: int, step: int = 10, chunk: int = 16) -> List[str]:
    lines = []
    line = start_line
    buffer: List[str] = []
    count = 0
    for byte in data:
        buffer.append(str(byte))
        count += 1
        if count == chunk:
            lines.append(f"{line} DATA " + ",".join(buffer))
            line += step
            buffer = []
            count = 0
    if buffer:
        lines.append(f"{line} DATA " + ",".join(buffer))
    return lines


def build_bitmap_basic_loader(
    manifest: Dict[str, Any],
    bitmap: bytes,
    screen: bytes,
    color: bytes,
) -> str:
    addresses = manifest["addresses"]
    vic = manifest["vic_registers"]
    background = manifest["palette"].get("background_color", 0) or 0
    border = manifest["palette"].get("border_color", background) or background

    lines = [
        "10 REM GENERATED BY C64-ULTIMATE-MCP",
        f"20 FOR I=0 TO {len(bitmap)-1}:READ A:POKE {addresses['bitmap']}+I,A:NEXT I",
        f"30 FOR I=0 TO {len(screen)-1}:READ A:POKE {addresses['screen']}+I,A:NEXT I",
        f"40 FOR I=0 TO {len(color)-1}:READ A:POKE {addresses['color']}+I,A:NEXT I",
        f"50 POKE 53265,{int(vic['d011'].replace('$',''),16)}",
        f"60 POKE 53270,{int(vic['d016'].replace('$',''),16)}",
        f"70 POKE 53272,{int(vic['d018'].replace('$',''),16)}",
        f"80 POKE 53280,{border}",
        f"90 POKE 53281,{background}",
        "100 END",
    ]

    lines += _data_lines(bitmap, 1000)
    lines += _data_lines(screen, 20000)
    lines += _data_lines(color, 30000)
    return "\n".join(lines) + "\n"


def build_sprite_basic_loader(
    manifest: Dict[str, Any],
    sprite_files: List[str],
) -> str:
    lines = [
        "10 REM GENERATED BY C64-ULTIMATE-MCP",
        "20 REM SPRITE DATA MUST BE LOADED FROM DISK OR POKED MANUALLY",
        "30 END",
    ]
    return "\n".join(lines) + "\n"
